import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="md:container md:mx-auto">
          <main className="">
            <nav className="flex justify-between items-center">
              <h1 className="text-3xl">
                <Link href="/">
                  Cringe-ier
                </Link>
              </h1>
              <div className="text-xl">
                <Link href="/admin">
                  Admin
                </Link>
              </div>
            </nav>
            {children}
            
          </main>
          <footer className="">
            
          </footer>
        </div>
      </body>
    </html>
  );
}
